trigger:
  branches:
    include:
      - test
  paths:
    include:
      - project/infra/*
      - azure-pipelines-provision.yml

pr: none

pool:
  vmImage: windows-latest

variables:
  azureServiceConnection: webe-demo-test
  terraformWorkingDirectory: project/infra
  resourceGroupName: rg-WEBE
  location: westeurope
  webAppName: thu-st-webe-demo-01
  easyAuth: true
  backendResourceGroupName: rg-tfstate
  backendStorageAccountName: thuifisttfwebe
  backendContainerName: tfstate
  backendStateKey: webapp-dev.tfstate

stages:
  - stage: Provision
    displayName: Provision infrastructure with Terraform
    jobs:
      - job: TerraformApply
        displayName: Terraform init, plan, apply
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: latest

          - task: TerraformTaskV4@4
            displayName: Terraform init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: $(terraformWorkingDirectory)
              backendServiceArm: $(azureServiceConnection)
              backendAzureRmResourceGroupName: $(backendResourceGroupName)
              backendAzureRmStorageAccountName: $(backendStorageAccountName)
              backendAzureRmContainerName: $(backendContainerName)
              backendAzureRmKey: $(backendStateKey)
            env:
              ARM_USE_AZUREAD: true
              ARM_STORAGE_USE_AZUREAD: true

          - task: TerraformTaskV4@4
            displayName: Terraform plan
            inputs:
              provider: azurerm
              command: plan
              workingDirectory: $(terraformWorkingDirectory)
              environmentServiceNameAzureRM: $(azureServiceConnection)
              commandOptions: >-
                -var "resource_group_name=$(resourceGroupName)"
                -var "location=$(location)"
                -var "webapp_name=$(webAppName)"
                -var "easyauth=$(easyAuth)"
            env:
              ARM_USE_AZUREAD: true
              ARM_STORAGE_USE_AZUREAD: true

          - task: TerraformTaskV4@4
            displayName: Terraform apply
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: $(terraformWorkingDirectory)
              environmentServiceNameAzureRM: $(azureServiceConnection)
              commandOptions: >-
                -auto-approve
                -var "resource_group_name=$(resourceGroupName)"
                -var "location=$(location)"
                -var "webapp_name=$(webAppName)"
                -var "easyauth=$(easyAuth)"
            env:
              ARM_USE_AZUREAD: true
              ARM_STORAGE_USE_AZUREAD: true
