trigger:
  branches:
    include:
      - test
      - prod

stages:
  - template: templates/deploy-webapp.yml
    parameters:
      stageName: Deploy_Test
      environmentName: test
      branchName: refs/heads/test
      resourceGroupName: rg-WEBE
      webAppName: thu-st-webe-demo-02
      azureServiceConnection: webe-demo-test

  - template: templates/deploy-webapp.yml
    parameters:
      stageName: Deploy_Prod
      environmentName: prod
      branchName: refs/heads/prod
      resourceGroupName: rg-WEBE-PROD
      webAppName: thu-st-webe-prod-02
      azureServiceConnection: webe-demo-prod